apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argoapp
spec:
  generators:
    - list:
        elements:
          - cluster: demo
            url: 'https://kubernetes.default.svc'
  template:
    metadata:
      name: '{{cluster}}-app'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/oaleev/mann-gitops-config.git'
        targetRevision: HEAD
      destination:
        server: '{{url}}'
        namespace: argoapp
