apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: mann-app-set
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - namespace: mann-app-set
      - namespace: new-app-set
  template:      
    metadata:
      name: '{{namespace}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/oaleev/mann-gitops-config.git
        targetRevision: HEAD
        path: ./manifests
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated:
          prune: true
          selfHeal: true      
